import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../person-button-feedback.js',import.meta.url),'utf8');
const listeners={},timers=new Map();let next=0,active=true;
const classes=new Set();const button={disabled:false,classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)}};
const badge={hidden:true,textContent:''};
const c={WeakMap,document:{getElementById:id=>id==='honnin'?{classList:{contains:()=>active}}:badge,addEventListener:(n,f)=>{listeners[n]=f;}},window:{addEventListener:(n,f)=>{listeners[n]=f;}},setTimeout:(f,ms)=>{const id=++next;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id)};
vm.runInNewContext(source,c);
const event={target:{closest:()=>button},button:0,isPrimary:true};
listeners.pointerdown(event);assert.ok(classes.has('person-press-held'));assert.equal(badge.hidden,true);
listeners.pointercancel();assert.equal(classes.size,0);assert.equal(badge.hidden,true);
listeners.click(event);assert.ok(classes.has('person-press-latched'));assert.equal(badge.textContent,'押しました');assert.equal(badge.hidden,false);
listeners.click(event);assert.equal(timers.size,2,'rapid presses replace timers');
for(const {f,ms} of [...timers.values()])if(ms===700)f();assert.equal(classes.size,0);assert.equal(badge.hidden,false);
for(const {f,ms} of [...timers.values()])if(ms===1400)f();assert.equal(badge.hidden,true);
button.disabled=true;listeners.click(event);assert.equal(badge.hidden,true);
button.disabled=false;active=false;listeners.click(event);assert.equal(badge.hidden,true);
console.log('button feedback: immediate press, cancel, persistence, keyboard click, disabled and mode isolation passed');
