import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('../household-ui.js',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'https://example.test',runScripts:'outside-only'});
const c=dom.getInternalVMContext(),d=dom.window.document;
let scrolled=0,resolveRegister,registerCalls=0;
const service={register:()=>{registerCalls++;return new Promise(resolve=>{resolveRegister=resolve;});},checkReady:async()=>({ready:false,status:'not-configured'}),resendVerification:async()=>{throw Error('確認メールを送れませんでした');}};
Object.assign(c,{recoveryBusy:false,getRecoveryService:()=>service,gid:()=> 'group',uid:()=> 'user',MainicoRecovery:{message:e=>e.message}});
d.getElementById('recovery-modal').classList.add('show');
d.getElementById('recovery-state').scrollIntoView=()=>{scrolled++;};
vm.runInContext(ui.slice(ui.indexOf('function recoveryState('),ui.indexOf('function getRecoveryService(')),c);
vm.runInContext(ui.slice(ui.indexOf('async function runRecoveryAction('),ui.indexOf('function getDeletionService(')),c);
const password=d.getElementById('recovery-password'),email=d.getElementById('recovery-email'),state=d.getElementById('recovery-state');
assert.ok(state.compareDocumentPosition(email)&4,'feedback precedes fields and controls, not hidden below the long footer');
email.value='test@example.test';password.value='test-only-password';
const running=c.runRecoveryAction('register');
assert.match(state.textContent,/確認しています/);assert.equal(d.getElementById('recovery-modal').getAttribute('aria-busy'),'true');
assert.ok([...d.querySelectorAll('#recovery-modal button')].every(b=>b.disabled));
await c.runRecoveryAction('register');assert.equal(registerCalls,1,'repeat clicks do not submit twice');
resolveRegister({ready:false});await running;
assert.equal(password.value,'','successful registration clears the password');assert.match(state.textContent,/確認メールを送りました/);
assert.ok([...d.querySelectorAll('#recovery-modal button')].every(b=>!b.disabled));
password.value='short';service.register=async()=>{throw Error('12文字以上で設定してください');};
await c.runRecoveryAction('register');assert.equal(password.value,'short','failed registration leaves input available for correction');
assert.match(state.textContent,/12文字以上/);assert.equal(state.classList.contains('err'),true);
await c.runRecoveryAction('check');assert.equal(password.value,'short');assert.match(state.textContent,/まだ登録されていません/);
await c.runRecoveryAction('resend');assert.equal(password.value,'short');assert.match(state.textContent,/送れませんでした/);
assert.ok(scrolled>=8,'progress, success and errors are scrolled into view');
assert.equal(d.getElementById('recovery-modal').getAttribute('aria-busy'),'false');
// Switch entry exposes login and resets consent every time it opens.
Object.assign(c,{auth:{currentUser:{uid:'user',isAnonymous:true}},recoverySwitchScope:null,renderRecoveryPointerSync:()=>{}});
vm.runInContext(ui.slice(ui.indexOf('async function openRecovery('),ui.indexOf('function closeRecovery(')),c);
await c.openRecovery(true);
assert.equal(d.getElementById('recovery-login').hidden,false);
// 復旧(ログイン)のときは、保存済みのパスワードを入れる欄・見出し
assert.equal(password.getAttribute('autocomplete'),'current-password');assert.equal(password.value,'');
assert.equal(d.getElementById('recovery-title').textContent,'使っていた記録に戻る');
assert.equal(d.getElementById('recovery-password-label').textContent,'登録したパスワード');
assert.equal(d.getElementById('recovery-register').hidden,true);
assert.equal(d.getElementById('recovery-switch-warning').hidden,false);
const consent=d.getElementById('recovery-leave-confirm');
consent.checked=true;await c.openRecovery(true);assert.equal(consent.checked,false);
let passed;
service.recover=async params=>{passed=params;throw Error('test login failure');};
consent.checked=true;password.value='existing-password';
await c.runRecoveryAction('login');
assert.equal(passed.leaveUnconfigured.uid,'user');assert.equal(passed.leaveUnconfigured.groupId,'group');
assert.equal(passed.leaveUnconfigured.noRecordsToKeep,true);assert.equal(password.value,'existing-password');
await c.openRecovery();assert.equal(d.getElementById('recovery-login').hidden,true);
// 設定(登録)のときは、新しいパスワードの欄。前に入れた値は残さない
assert.equal(password.getAttribute('autocomplete'),'new-password');assert.equal(password.value,'');
assert.match(d.getElementById('recovery-title').textContent,/復旧の設定/);
assert.match(d.getElementById('recovery-password-label').textContent,/新しいパスワード（12文字以上/);
assert.equal(d.getElementById('recovery-register').hidden,false);
// すでにパスワードで登録済みの人が設定を開いたときは、登録したパスワードを入れる欄
c.auth.currentUser={uid:'user',isAnonymous:false,email:'a@example.com',providerData:[{providerId:'password'}]};
await c.openRecovery();
assert.equal(password.getAttribute('autocomplete'),'current-password');
assert.equal(d.getElementById('recovery-password-label').textContent,'登録したパスワード');
assert.equal(d.getElementById('recovery-switch-warning').hidden,true);
dom.window.close();
console.log('recovery feedback: register/login autocomplete and titles, visible progress/results, preserved retry input, success clearing and duplicate-submit guard passed');
