import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('../household-ui.js',import.meta.url),'utf8');
const dom=new JSDOM(html,{url:'https://example.test',runScripts:'outside-only'});
const c=dom.getInternalVMContext(),d=dom.window.document;
let scrolled=0,resolveRegister,registerCalls=0;
const service={register:()=>{registerCalls++;return new Promise(resolve=>{resolveRegister=resolve;});},checkReady:async()=>({ready:false,status:'not-configured'}),resendVerification:async()=>{throw Error('確認メールを送れませんでした');}};
Object.assign(c,{recoveryBusy:false,getRecoveryService:()=>service,gid:()=> 'group',uid:()=> 'user',MainicoRecovery:{message:e=>e.message}});
d.getElementById('recovery-modal').classList.add('show');
d.getElementById('recovery-state').scrollIntoView=()=>{scrolled++;};
vm.runInContext(ui.slice(ui.indexOf('function recoveryState('),ui.indexOf('function getRecoveryService(')),c);
vm.runInContext(ui.slice(ui.indexOf('async function runRecoveryAction('),ui.indexOf('function getDeletionService(')),c);
const password=d.getElementById('recovery-password'),email=d.getElementById('recovery-email'),state=d.getElementById('recovery-state');
assert.ok(state.compareDocumentPosition(email)&4,'feedback precedes fields and controls, not hidden below the long footer');
email.value='test@example.test';password.value='test-only-password';
const running=c.runRecoveryAction('register');
assert.match(state.textContent,/確認しています/);assert.equal(d.getElementById('recovery-modal').getAttribute('aria-busy'),'true');
assert.ok([...d.querySelectorAll('#recovery-modal button')].every(b=>b.disabled));
await c.runRecoveryAction('register');assert.equal(registerCalls,1,'repeat clicks do not submit twice');
resolveRegister({ready:false});await running;
assert.equal(password.value,'','successful registration clears the password');assert.match(state.textContent,/確認メールを送りました/);
assert.ok([...d.querySelectorAll('#recovery-modal button')].every(b=>!b.disabled));
password.value='short';service.register=async()=>{throw Error('12文字以上で設定してください');};
await c.runRecoveryAction('register');assert.equal(password.value,'short','failed registration leaves input available for correction');
assert.match(state.textContent,/12文字以上/);assert.equal(state.classList.contains('err'),true);
await c.runRecoveryAction('check');assert.equal(password.value,'short');assert.match(state.textContent,/まだ登録されていません/);
await c.runRecoveryAction('resend');assert.equal(password.value,'short');assert.match(state.textContent,/送れませんでした/);
assert.ok(scrolled>=8,'progress, success and errors are scrolled into view');
assert.equal(d.getElementById('recovery-modal').getAttribute('aria-busy'),'false');
dom.window.close();
console.log('recovery feedback: visible progress/results, preserved retry input, success clearing and duplicate-submit guard passed');
