import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf("let familyConnection={"),html.indexOf('let personTasksController=null;'));
const labels=[{textContent:''}],requests=[{textContent:''}],people=[{textContent:''}];
let account='me',group='home',listeners=[],stops=0;
const c={document:{querySelectorAll:sel=>sel==='[data-connection-state]'?labels:sel==='[data-request-audience]'?requests:people,getElementById:()=>null},uid:()=>account,gid:()=>group,householdBootGeneration:1,MainicoFamilyConnection:require('../family-connection.js'),col:()=>({onSnapshot:(opt,ok,err)=>{listeners.push({ok,err});return ()=>stops++;}})};
vm.createContext(c);vm.runInContext(source,c);
const snap=(members,cache=false)=>({metadata:{fromCache:cache},forEach:fn=>members.forEach(([id,role,status='approved'])=>fn({id,data:()=>({role,status})}))});
c.startFamilyConnection();assert.match(labels[0].textContent,/確認できません/);
listeners[0].ok(snap([['me','honnin']]));assert.match(labels[0].textContent,/ほかの承認済み参加者はいません/);assert.match(requests[0].textContent,/家族の参加は確認されていません/);
listeners[0].ok(snap([['me','honnin'],['family','kazoku']]));assert.match(labels[0].textContent,/1人/);assert.match(requests[0].textContent,/確認や対応は保証されません/);
listeners[0].ok(snap([['me','honnin']],true));assert.doesNotMatch(labels[0].textContent,/参加者はいません/);
listeners[0].err();assert.match(labels[0].textContent,/確認できません/);
c.startFamilyConnection();assert.equal(stops,1);listeners[0].ok(snap([['me','honnin'],['old','kazoku']]));assert.doesNotMatch(labels[0].textContent,/1人/);
account='new';group='newhome';listeners[1].ok(snap([['me','honnin']]));assert.doesNotMatch(labels[0].textContent,/参加者はいません/);
c.stopFamilyConnection();assert.equal(stops,2);
assert.match(html,/onclick="openPersonTasks\(\)"/);
assert.match(html,/招待せずに一人で始められます/);
assert.match(html,/あとから参加を承認した家族には、これまでの予定・記録・やることも共有/);
assert.doesNotMatch(html,/家族の画面に届けました|家族の画面に記録されました|家族へ伝言を共有しました/);
assert.match(html,/function initHonnin\(\)\{\s*startFamilyConnection/);
assert.match(html,/function initKazoku\(\)\{\s*startFamilyConnection/);
const lifecycle=fs.readFileSync(new URL('../household-ui.js',import.meta.url),'utf8');
assert.match(lifecycle,/function stopHouseholdSubscriptions\(\)\{[\s\S]*?stopFamilyConnection\(\);[\s\S]*?closePersonTasks\(\);/);
console.log('solo integration: unknown/solo/shared/cache/error/stale callbacks and lifecycle passed');
